{% set name = "sirepo-bluesky" %}
{% set version = "0.3.0" %}
{% set sha256 = "5440f04e48997bab5c93ef34dc954def4d9eab757bc724b1f4f6aae15f40ab67" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bluesky
    - databroker
    - ipython
    - matplotlib
    - numconv
    - numpy
    - ophyd
    - pymongo
    - pyqt >=5.9
    - python
    - requests
    - srwpy
    - unyt

test:
  imports:
    - sirepo_bluesky

about:
  home: https://github.com/NSLS-II/sirepo-bluesky
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sirepo-Bluesky interface
